# Choose a default "cargo run" tool.
# probe-run is recommended if you have a debugger
# elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"
#runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"

# thumbv6m-none-eabi is not coming with core and alloc, compile myself
[unstable]
mtime-on-use = true
# either run `rustup target add --toolchain nightly thumbv6m-none-eabi`
# or uncomment the next line to build core yourself, self-buildings allows LTO
# to optimise better
# build-std = [ "core"]